### ISSUE TITLE
Allow subcontent entries

### ISSUE THREAD

**Issue by Blesmol** [Blesmol/pfsct#28]
For some use-cases it makes sense if content entries can have (named or unnamed) subcontent entries. Everything else would be just stupid workarounds.

Some possible use-case examples that do not necessarily resemble working content:

### Example 1
```
Usage: tier=high

tier:
  type: choice
  subcontent:
    low:
      type: crossSomethingOut
      x1: ...
    high:
      type: crossSomethingOut
      x1: ...
```

### Example 2
```
Usage: gm_initials=MJ (relevant, e.g., for Starfinder)

gm_initials:
  type: multivalue
  subcontent:
    - type: textCell
       x1: ...
    - type: texCell
      x1: ...
```
