### ISSUE TITLE
Automatically calculate things like gold from treasure bundles and char level

### ISSUE THREAD

**Issue by Blesmol** [Blesmol/pfsct#36]
A proposal was made that it would be good to have functionality that would automatically calculate the gold a character receives based on the characters level and the number of treasure bundles that the character received.

This should not replace the current option to provide a gold value directly, but merely be an alternative option. It would require that also the char level is provided, which is currently not done, as it does not appear anywhere on the chronicle sheets. And it would also require to keep the table somehow in the game-specific template.

**Comment by tdhsmith** [comment]
I was thinking the easiest way to do this would be defining some way to do an indirection via a lookup table in YAML. Something like a block of "computations" or "conversions". So a quest could have:
```yml
parameters:
  "Player Info:"
    level:
      type: text
      description: Character's level
      example: 2

conversions:
  gold_by_level:
    source: param:level
    target: param:gp
    lookup_table:
      1: 3.5 gp
      2: 5.5 gp
      3: 9.5 gp
      # etc...
```

However that's not going to fly for scenarios, whose rewards are parameterized by both level _and_ the number of treasure bundles recovered.

One could set up a whole math parser and then define the computations as arithmetic expressions, but that seems like a lot of work for this feature, especially when this is about the only use case.
