### ISSUE TITLE
Values in right bar missaligned for some scenarios

### ISSUE THREAD

**Issue by Lonwyr** [Blesmol/pfsct#47]
The chronicle sheets position on the page itself changes from adventure to adventure.

This leads to a wrong positioning of the labels.
I.e. In #1-06 the player & character name overlaps with the scenario title itself.

**Comment by Blesmol** [comment]
Yes, I also saw that and am working on providing a fix. This fix will roughly look as follows:
* Coordinates are no longer provided in points, but in percent, i.e. page coordinates have a range from 0.0 to 100.0 => already done
* It will be possible to provide an offset for certain values so that e.g. all coordinates from the right bar (incl. XP, gold, etc) will use the same offset
* With that and the existing inheritance mechanism it will be possible to have a configuration for a specific template that basically only provides the offset.

This would mean that in the future there is a template with (example) ID `pfs2:s01-17`, and that would probably somehow like this:
```
id: pfs2:s01-17
inherit: pfs2
presets:
  rightbaroffset:
    y: 20.0
```

Currently I am still heavily restructuring the internal data model, but that is the next thing on the agenda to get things going. Thanks for pointing out!

**Comment by Blesmol** [comment]
Fixes are included in release v0.9.0. Configurations were added for all chronicles where the sidebar has different coordinates where I am aware of this. If something is missing, adding a fixed config is quite easy. For example, the whole config for scenario 1-18 looks as follows:
```
id: pfs2.s1-18
description: "PFS2 #1-18: Lodge of the Living God"
inherit: pfs2.s01

presets:
  rightbarposy:
    y:  28.6
    y2: 90.8
```

This means, of course, that instead of `pfs2` the new template id `pfs2.s1-18` needs to be used for this to become effective.
